### ISSUE TITLE
Error while converting pytorch to caffe

### ISSUE THREAD

**Issue by soham24** [miaow1988/ShuffleNet_V2_pytorch_caffe#22]
Traceback (most recent call last):
  File "shufflenet_v2.py", line 224, in <module>
    net.convert_to_caffe(args.save_caffe)
  File "shufflenet_v2.py", line 160, in convert_to_caffe
    print(caffe_net.to_proto())
  File "/home/orbosoham/freshCaffe/caffe/python/caffe/net_spec.py", line 193, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/orbosoham/freshCaffe/caffe/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/orbosoham/freshCaffe/caffe/python/caffe/net_spec.py", line 162, in _to_proto
    assign_proto(layer, k, v)
  File "/home/orbosoham/freshCaffe/caffe/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: group

**Comment by soham24** [comment]
after looking at  [issue 5](https://github.com/miaow1988/ShuffleNet_V2_pytorch_caffe/issues/5)What I understood is that I need to add ShuffleChannel layer in caffe.  I am complete newbie to caffe. Can you enlight me about the steps for doing the same.

**Comment by soham24** [comment]
solution : build caffe with shufflechannel layer
